[package]
name = "audio_plus"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"

[dependencies]
bevy = "0.8.0"
bevy_kira_audio = "0.11.0"

[dev-dependencies]
examples_common = { path = "crates/examples_common" }
rand = "0.8.5"